version: "3"
services:
  api:
    build: .
    depends_on:
      - database
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=mypasswd
      - DATABASE=postgres
  database:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=mypasswd
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
