version: "3.9"
services:
  database:
    container_name: taskman_db
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=mypasswd
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 6000:5432
volumes:
  postgres_db:
